clusters:
- name: in-cluster
  server: https://kubernetes.default.svc
  env: dev
- name: uddhao-dpc
  server: http://cluster-uddhao-dpc:8001
  env: test1
- name: test-dpc
  server: http://cluster-test-dpc:8001
  env: test2
- name: test-tara
  server: http://cluster-test-tara:8001
  env: test3
